### ISSUE TITLE
I'm not sure how to use this library

### ISSUE THREAD

**Issue by siderakis** [rome2rio/react-native-touch-through-view#15]
I would expect the entire green section to be press-able, but only the section that is not covered is press-able. I only tried on iOS.

Thanks for any pointers!

import {
  FlatView,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableHighlight,
  View,
} from "react-native"
import React, { Component } from "react"
import {
  TouchThroughView,
  TouchThroughWrapper,
} from "react-native-touch-through-view"

type Props = {}
export default class App extends Component<Props> {
  render() {
    return (
      <View style={{ flex: 1 }}>
        <TouchThroughWrapper style={{ flex: 1 }}>
          <ScrollView>
            <TouchableHighlight onPress={() => alert("hi")}>
              <View
                style={{
                  height: 300,
                  position: "absolute",
                  top: 0,
                  left: 0,
                  right: 0,

                  backgroundColor: "green",
                }}
              />
            </TouchableHighlight>
            <TouchThroughView
              style={{
                backgroundColor: "#ff000010",
                height: 200,
              }}
            />
          </ScrollView>
        </TouchThroughWrapper>
      </View>
    )
  }
}

**Comment by traviswimer** [comment]
Did you intend to close this issue?

Anyway, FYI, I think the NPM package is being transferred to use this fork: https://github.com/simonhoss/react-native-touch-through-view

I'm not sure if that would make a difference in your case.

That being said, aren't your elements overlapping because of `position: absolute`? I imagine that is part of your problem.
